# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  # push:
  #   branches: [ "master" ]
  #   paths:
  #     - "public/**"
  #     - "src/**"
  #     - ".github/workflows/node.js.yml"
  #     - "package-lock.json"
  #     - "package.json"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set CI environment variable to false
      run: echo "CI=false" >> $GITHUB_ENV  # 設置CI為false
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Cache Node.js
      uses: actions/cache@v4.2.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci
    - run: npm run build --if-present

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
        retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # 部署到 gh-pages 分支
        publish_dir: build  # 指向 build 資料夾
        force_orphan: true  # 強制創建孤立分支，刪除歷史記錄
