name: 部署 React 應用到 GitHub Pages

on:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 檢測環境
        uses: actions/checkout@v4

      - name: 設置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.0"

      - name: 安裝依賴
        run: npm ci

      - name: 構建 React 應用
        run: npm run build

      - name: 配置頁面
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build" # 或者 './dist'，取決於您的構建配置

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
