name: 同步復刻

on:
  schedule:
    # 台灣時間午夜 00:00 (UTC+8) 相當於 UTC 16:00 (前一天)
    - cron: '0 16 * * *'
  workflow_dispatch: # 允許手動觸發

permissions:
  contents: write # 給予寫入權限

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 檢測是否為復刻倉庫
        id: check-fork
        run: |
          REPO_FULL_NAME="${GITHUB_REPOSITORY}"
          UPSTREAM_REPO_URL="$(git config --get remote.origin.url)"

          # 檢測是否有上遊倉庫
          if git remote -v | grep -q upstream; then
            echo "這是復刻倉庫，已存在上遊遠程"
            echo "IS_FORK=true" >> $GITHUB_OUTPUT
          else
            # 嘗試從 API 獲取 fork 信息
            REPO_INFO=$(curl -s -H "Authorization: token ${{ github.token }}" \
              "https://api.github.com/repos/${REPO_FULL_NAME}")

            if echo "$REPO_INFO" | grep -q '"fork": true'; then
              echo "這是復刻倉庫，需要添加上遊遠程"
              PARENT_REPO=$(echo "$REPO_INFO" | grep -o '"parent":.*"clone_url":"[^"]*"' | grep -o '"clone_url":"[^"]*"' | cut -d'"' -f4)
              echo "上遊倉庫 URL: $PARENT_REPO"
              git remote add upstream $PARENT_REPO
              echo "IS_FORK=true" >> $GITHUB_OUTPUT
            else
              echo "這是原始倉庫，不需要同步"
              echo "IS_FORK=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: 配置 Git
        if: steps.check-fork.outputs.IS_FORK == 'true'
        run: |
          git config --global user.name "Canaan-HS"
          git config --global user.email "s3459897@gmail.com"
          echo "已配置 Git 用戶信息"

      - name: 同步分支
        if: steps.check-fork.outputs.IS_FORK == 'true'
        run: |
          echo "開始同步分支..."
          git fetch upstream

          # 檢查是否有更新
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse upstream/master)

          if [ "$LOCAL" = "$REMOTE" ]; then
            echo "已經是最新狀態，無需同步"
          else
            echo "檢測到上遊更新，開始同步..."
            git checkout master
            git merge upstream/master --no-edit
            git push origin master
            echo "同步完成！"
          fi
